#!/usr/bin/env bash

# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -euo pipefail

# for debugging
# set -x

echo "setup starting"

echo "creating ~/.bash_aliases"

cat aliases > ~/.bash_aliases

echo "setup finished"
